from applied_computer_science_discord_bot.message_handlers.virtual_message_handler import Handler, CommandHandler, ParsedCommand
from applied_computer_science_discord_bot.message_handlers.test_handler import TestHandler
from applied_computer_science_discord_bot.message_handlers.print_handler import PrintHandler
from applied_computer_science_discord_bot.message_handlers.delete_messages_handler import DeleteMessagesHandler
