from applied_computer_science_discord_bot.message_handlers.virtual_message_handler import Handler, CommandHandler, ParsedCommand
from applied_computer_science_discord_bot.message_handlers.test_handler import TestHandler
